#!/usr/bin/env python3

cronograma = {
    '01': ('Plano de ensino', 1),
    '02': ('Construção e representação geométrica dos números complexos', 1),
    '03': ('Propriedades algébricas, complexo conjugado', 1),
    '04': ('Módulo, propriedades: desigualdade triangular', 1),
    '05': ('Representação polar, raízes de números complexos', 1),
    '06': ('Noções de topologia dos complexos', 1),
    '07': ('Funções e seus limites': 1),
    '07': ('Propriedades dos limites, Teoremas', 1),
    '08': ('Limites envolvendo o ponto no infinito, continuidade', 1)
    '09': ('Derivadas e regras de derivação ', 1),
    '10': ('As equações de Cauchy-Riemann, coordenadas polares', 1),
    '11': ('Condições suficientes para derivabilidade, funções analíticas', 1),
    '12': ('Funções harmônicas, unicidade de funções analíticas', 1),
    '13': ('As funções exponencial e logarítmica e suas derivadas', 1),
    '14': ('Identidades envolvendo logarítmos, potências', 1),
    '15': ('As funções trigonométricas: seno e cosseno', 1),
    '16': ('Zeros e singularidades das funções trigonométricas', 1),
    '17': ('Funções hiperbólicas', 1),
    '18': ('Funções trigonométricas e hiperbólicas inversas', 1),
    '19': ('Aula de exercícios', 1),
    '20': ('Primeira prova escrita', 1),
    '21': ('Caminhos', 1),
    '22': ('Integrais ao longo de caminhos', 1),
    '23': ('Propriedades da integral, desigualdade triangular', 1),
    '24': ('Primitivas', 1),
    '25': ('Teoremas de Green e de Cauchy-Goursat', 1),
    '26': ('Fórmula integral de Cauchy, derivadas de ordem superior', 1)
    '27': ('Teorema Fundamental da Álgebra', 1),
    '28': ('Sequências de números complexos', 1),
    '29': ('Séries de números complexos', 1)
    '30': ('Séries de Taylor', 1),
    '31': ('Séries de Laurent', 1),
    '32': ('Aula de exercícios', 1),
    '33': ('Segunda prova escrita', 1),
    '34': ('Seminários: 1) Singularidades e resíduos; e 2) Teorema do Resíduos', 1),
    '35': ('Seminários: 3) Resíduos em polos; e 4) Zeros de funções analíticas', 1),
    '36': ('Seminários: 5) Zeros e polos; e 6) Comportamento próximo a singularidades isoladas', 1),
    '37': ('Seminários: 7) Cálculo de integrais impróprias; e 8) Integrais impróprias da Análise de Fourier', 1),
    '38': ('Seminários: 9) Integrais definidas envolvendo seno; e 1) Integrais definidas envolvendo cosseno', 1),
}
